### ISSUE TITLE
Don't get gdrive_creds.json

### ISSUE THREAD

**Issue by midiexianghhh** [lcn-kul/conferencing-speech-2022#1]
I followed this README:

Follow [these instructions](https://cloud.google.com/docs/authentication/getting-started#creating_a_service_account) to create a Google Cloud project and Service Key. After following these instructions, you will have downloaded a JSON file containing your Google credentials. Place this JSON file in the following location:
   location:
   ```
   conferencing-speech-2022/gdrive_creds.json
   ```

but I don't get this gdrive_creds.json, could u tell me the detail about getting gdrive_creds.json? Does the gdrive_creds.json will getting via chrome downloading or shell generating?
 
thanks for your time!

**Comment by btamm12** [comment]
Thanks for opening the issue. Since creating the repository, Google has updated its cloud platform and the hyperlink now redirects to the wrong instructions!
